### ISSUE TITLE
error in api calling

### ISSUE THREAD

**Issue by mrcool17** [jmolins/flutboard#1]
E/flutter (27336): [ERROR:flutter/shell/common/shell.cc(93)] Dart Unhandled Exception: Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as arguments.: Closure: (HttpException) => Null, stack trace: #0      Stream.handleError (dart:async/stream.dart:666:7)
E/flutter (27336): #1      IOClient.send (package:http/src/io_client.dart:52:55)
E/flutter (27336): <asynchronous suspension>
E/flutter (27336): #2      BaseClient._sendUnstreamed (package:http/src/base_client.dart:176:32)
E/flutter (27336): <asynchronous suspension>
E/flutter (27336): #3      _withClient (package:http/http.dart:166:12)
E/flutter (27336): <asynchronous suspension>
E/flutter (27336): #4      Api.getArticles (package:flutboard/service/api.dart:20:32)
E/flutter (27336): <asynchronous suspension>
E/flutter (27336): #5      ArticleBloc._getArticles (package:flutboard/service/article_bloc.dart:79:25)
E/flutter (27336): <asynchronous suspension>
E/flutter (27336): #6      ArticleBloc.getArticles (package:flutboard/service/article_bloc.dart:58:20)
E/flutter (27336): <asynchronous suspension>

**Comment by jmolins** [comment]
@mrcool17  I have updated the app to null safety, upgraded packages and corrected some bugs.
This should be fixed.
Please, let me know otherwise.
